### ISSUE TITLE
No exe file

### ISSUE THREAD

**Issue by splez** [nippur72/SqlServerSocket#3]
sorry there is no exe file, how am im supposed to run this, im kind of new to github...

**Comment by IQaiserHussain** [comment]
This is my issue as well!

**Comment by nippur72** [comment]
sorry this is an old project I am no longer maintaining it -- anyhow it was meant to be open from Visual Studio (not VS Code) and produce the `.exe` from there. I have not included the `.exe` here for security reasons.

**Comment by splez** [comment]
thanks :)
